Remove beautify css
beautify.css was removed from deform in

https://github.com/Pylons/deform/commit/366355c17b334f5c203e443453f85bda47161abd

Fixes error:

```
  File "/app/.venv/lib/python3.7/site-packages/js/deform/__init__.py", line 39, in <module>

    "css/beautify.css")

  File "/app/.venv/lib/python3.7/site-packages/fanstatic/core.py", line 400, in __init__

    "Resource file does not exist: %s" % path)

fanstatic.core.UnknownResourceError: Resource file does not exist: /app/.venv/lib/python3.7/site-packages/deform/static/css/beautify.css
```